import {
  Box,
  Container,
  Fab,
  List,
  ListSubheader,
  Typography,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import Exercice from "src/features/exercices/components/Exercice";
import { selectExercices } from "src/features/store/exercisesSlice";
import AddIcon from "@mui/icons-material/Add";
import NextLinkComposed from "src/features/components/NextLinkComposed";
import Header from "src/features/components/Header";
// interface ExerciceProps {
//   name: string;
//   description?: string;
// }

// const Exercice: React.FC<Exercice> = ({ name, slug, description }) => {
//   return (
//     <Link href={`/exercice/${slug}`}>
//       <a className="row">
//         <div className="mb-2">
//           <span className="title">{name}</span>
//         </div>
//         <p className="description">{description}</p>
//       </a>
//     </Link>
//   );
// };

const Home: NextPage = () => {
  const exercices = useSelector(selectExercices);

  useEffect(() => {
    console.log(exercices);
  }, [exercices]);

  return (
    <div className="container">
      <Head>
        <title>Trainer sheets</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Container>
        <Header>Accueil</Header>

        <List component="nav">
          <ListSubheader disableGutters>Non catégorisé (0)</ListSubheader>
          {exercices.map((exercice) => (
            <Exercice key={exercice.slug} {...exercice} />
          ))}
        </List>
      </Container>

      <Fab
        color="primary"
        component={NextLinkComposed}
        href={`/exercice/add`}
        sx={{ position: "absolute", bottom: 16, right: 16 }}
      >
        <AddIcon />
      </Fab>
    </div>
  );
};

export default Home;
